// prebuilt-decks.data.js
// Все готовые колоды и их карточки

const PREBUILT_DECKS = [
  // ── АНГЛИЙСКИЙ ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: '100 основных английских слов',
    language: 'en',
    description: 'Самые часто используемые английские слова — идеально для старта',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 30,
    tags: ['базовый', 'начальный', 'частотный'],
    author: 'LinguaCards Team',
    popularity: 98,
  },
  {
    id: 2,
    name: 'Деловой английский',
    language: 'en',
    description: 'Ключевые слова и фразы для деловой переписки, переговоров и презентаций',
    category: 'business',
    difficulty: 'advanced',
    card_count: 25,
    tags: ['бизнес', 'профессиональный', 'переговоры'],
    author: 'LinguaCards Team',
    popularity: 91,
  },
  {
    id: 3,
    name: 'Английский для путешествий',
    language: 'en',
    description: 'Всё необходимое для поездки: аэропорт, отель, ресторан, шопинг',
    category: 'travel',
    difficulty: 'beginner',
    card_count: 25,
    tags: ['путешествия', 'туризм', 'практический'],
    author: 'LinguaCards Team',
    popularity: 94,
  },
  {
    id: 4,
    name: 'Неправильные глаголы английского',
    language: 'en',
    description: 'Все неправильные глаголы с тремя формами — must know для грамматики',
    category: 'grammar',
    difficulty: 'intermediate',
    card_count: 25,
    tags: ['грамматика', 'глаголы', 'неправильные'],
    author: 'LinguaCards Team',
    popularity: 96,
  },

  // ── ИСПАНСКИЙ ────────────────────────────────────────────────────────────────
  {
    id: 5,
    name: 'Испанский для начинающих',
    language: 'es',
    description: 'Первые 50 слов и фраз для старта изучения испанского',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 25,
    tags: ['базовый', 'начальный', 'разговорный'],
    author: 'LinguaCards Team',
    popularity: 87,
  },
  {
    id: 6,
    name: 'Испанские глаголы',
    language: 'es',
    description: 'Самые употребляемые глаголы с примерами использования',
    category: 'grammar',
    difficulty: 'intermediate',
    card_count: 20,
    tags: ['глаголы', 'грамматика', 'спряжение'],
    author: 'LinguaCards Team',
    popularity: 82,
  },

  // ── НЕМЕЦКИЙ ─────────────────────────────────────────────────────────────────
  {
    id: 7,
    name: 'Немецкие существительные с артиклями',
    language: 'de',
    description: 'Основные существительные с правильными артиклями der/die/das',
    category: 'grammar',
    difficulty: 'intermediate',
    card_count: 25,
    tags: ['грамматика', 'существительные', 'артикли'],
    author: 'LinguaCards Team',
    popularity: 79,
  },
  {
    id: 8,
    name: 'Немецкий для начинающих',
    language: 'de',
    description: 'Базовые слова и фразы для первого знакомства с немецким языком',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['базовый', 'начальный', 'разговорный'],
    author: 'LinguaCards Team',
    popularity: 75,
  },

  // ── ФРАНЦУЗСКИЙ ──────────────────────────────────────────────────────────────
  {
    id: 9,
    name: 'Французские фразы для ресторана',
    language: 'fr',
    description: 'Полезные фразы для заказа еды и общения в ресторанах Франции',
    category: 'food',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['ресторан', 'еда', 'диалоги'],
    author: 'LinguaCards Team',
    popularity: 88,
  },
  {
    id: 10,
    name: 'Французский для начинающих',
    language: 'fr',
    description: 'Базовый словарный запас для начала изучения французского',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['базовый', 'начальный', 'приветствия'],
    author: 'LinguaCards Team',
    popularity: 83,
  },

  // ── ИТАЛЬЯНСКИЙ ──────────────────────────────────────────────────────────────
  {
    id: 11,
    name: 'Итальянский для туристов',
    language: 'it',
    description: 'Всё необходимое для путешествия по Италии',
    category: 'travel',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['путешествия', 'туризм', 'Италия'],
    author: 'LinguaCards Team',
    popularity: 81,
  },
  {
    id: 12,
    name: 'Итальянские прилагательные',
    language: 'it',
    description: 'Описательные прилагательные для повседневного общения',
    category: 'vocabulary',
    difficulty: 'intermediate',
    card_count: 20,
    tags: ['прилагательные', 'описания', 'разговорный'],
    author: 'LinguaCards Team',
    popularity: 71,
  },

  // ── ЯПОНСКИЙ ─────────────────────────────────────────────────────────────────
  {
    id: 13,
    name: 'Японский: хирагана',
    language: 'ja',
    description: 'Все 46 символов хираганы с произношением — первый шаг к японскому',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['хирагана', 'алфавит', 'письмо'],
    author: 'LinguaCards Team',
    popularity: 92,
  },
  {
    id: 14,
    name: 'Японский для путешествий',
    language: 'ja',
    description: 'Базовые фразы и слова для поездки в Японию',
    category: 'travel',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['путешествия', 'Япония', 'разговорный'],
    author: 'LinguaCards Team',
    popularity: 85,
  },

  // ── КИТАЙСКИЙ ────────────────────────────────────────────────────────────────
  {
    id: 15,
    name: 'Китайский: базовые иероглифы',
    language: 'zh',
    description: '50 самых распространённых иероглифов с произношением пиньинь',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['иероглифы', 'пиньинь', 'базовый'],
    author: 'LinguaCards Team',
    popularity: 89,
  },
  {
    id: 16,
    name: 'Китайский: числа и время',
    language: 'zh',
    description: 'Числа, дни недели, месяцы — основа для повседневного общения',
    category: 'basic',
    difficulty: 'beginner',
    card_count: 20,
    tags: ['числа', 'время', 'дни'],
    author: 'LinguaCards Team',
    popularity: 76,
  },
];

const PREBUILT_CARDS = {
  // ── 1: 100 основных английских слов ─────────────────────────────────────────
  1: [
    { front_text: 'Hello', back_text: 'Привет', example: 'Hello! How are you?' },
    { front_text: 'Goodbye', back_text: 'До свидания', example: 'Goodbye! See you tomorrow!' },
    { front_text: 'Thank you', back_text: 'Спасибо', example: 'Thank you for your help.' },
    { front_text: 'Please', back_text: 'Пожалуйста', example: 'Can I have some water, please?' },
    { front_text: 'Sorry', back_text: 'Извините', example: 'Sorry, I am late.' },
    { front_text: 'Yes', back_text: 'Да', example: 'Yes, I understand.' },
    { front_text: 'No', back_text: 'Нет', example: 'No, thank you.' },
    { front_text: 'Good', back_text: 'Хорошо / Хороший', example: 'That is a good idea.' },
    { front_text: 'Bad', back_text: 'Плохо / Плохой', example: 'This is bad news.' },
    { front_text: 'Big', back_text: 'Большой', example: 'This is a big city.' },
    { front_text: 'Small', back_text: 'Маленький', example: 'I have a small dog.' },
    { front_text: 'New', back_text: 'Новый', example: 'I bought a new phone.' },
    { front_text: 'Old', back_text: 'Старый', example: 'This is an old building.' },
    { front_text: 'Water', back_text: 'Вода', example: 'Can I have some water?' },
    { front_text: 'Food', back_text: 'Еда', example: 'I love Italian food.' },
    { front_text: 'House', back_text: 'Дом', example: 'This is my house.' },
    { front_text: 'Car', back_text: 'Машина', example: 'I drive a red car.' },
    { front_text: 'Book', back_text: 'Книга', example: 'I am reading a book.' },
    { front_text: 'Time', back_text: 'Время', example: 'What time is it?' },
    { front_text: 'Day', back_text: 'День', example: 'Have a nice day!' },
    { front_text: 'Night', back_text: 'Ночь', example: 'Good night!' },
    { front_text: 'Morning', back_text: 'Утро', example: 'Good morning!' },
    { front_text: 'Work', back_text: 'Работа', example: 'I go to work every day.' },
    { front_text: 'School', back_text: 'Школа', example: 'My children go to school.' },
    { front_text: 'Friend', back_text: 'Друг', example: 'He is my best friend.' },
    { front_text: 'Family', back_text: 'Семья', example: 'I love my family.' },
    { front_text: 'Money', back_text: 'Деньги', example: 'I need some money.' },
    { front_text: 'Love', back_text: 'Любовь', example: 'Love is important.' },
    { front_text: 'Happy', back_text: 'Счастливый', example: 'I am very happy today.' },
    { front_text: 'Beautiful', back_text: 'Красивый', example: 'What a beautiful day!' },
  ],

  // ── 2: Деловой английский ────────────────────────────────────────────────────
  2: [
    { front_text: 'Meeting', back_text: 'Совещание', example: 'We have a meeting at 10 AM.' },
    { front_text: 'Deadline', back_text: 'Дедлайн', example: 'The deadline is Friday.' },
    { front_text: 'Budget', back_text: 'Бюджет', example: 'We need to cut the budget.' },
    { front_text: 'Proposal', back_text: 'Предложение', example: 'Please review this proposal.' },
    { front_text: 'Agreement', back_text: 'Соглашение', example: 'We signed an agreement.' },
    { front_text: 'Strategy', back_text: 'Стратегия', example: 'Our strategy is working.' },
    { front_text: 'Revenue', back_text: 'Выручка', example: 'Revenue increased by 20%.' },
    { front_text: 'Negotiation', back_text: 'Переговоры', example: 'The negotiation was successful.' },
    { front_text: 'Partnership', back_text: 'Партнёрство', example: 'We formed a new partnership.' },
    { front_text: 'Invoice', back_text: 'Счёт-фактура', example: 'Please send the invoice.' },
    { front_text: 'Presentation', back_text: 'Презентация', example: 'I prepared a presentation.' },
    { front_text: 'Colleague', back_text: 'Коллега', example: 'My colleague helped me.' },
    { front_text: 'Client', back_text: 'Клиент', example: 'The client is satisfied.' },
    { front_text: 'Project', back_text: 'Проект', example: 'The project is on track.' },
    { front_text: 'Profit', back_text: 'Прибыль', example: 'We made a good profit.' },
    { front_text: 'Report', back_text: 'Отчёт', example: 'Please submit the report.' },
    { front_text: 'Schedule', back_text: 'График', example: 'Are you on schedule?' },
    { front_text: 'Feedback', back_text: 'Обратная связь', example: 'I appreciate your feedback.' },
    { front_text: 'Priority', back_text: 'Приоритет', example: 'This is our top priority.' },
    { front_text: 'Efficiency', back_text: 'Эффективность', example: 'Improve team efficiency.' },
    { front_text: 'Stakeholder', back_text: 'Заинтересованная сторона', example: 'Inform all stakeholders.' },
    { front_text: 'Outsource', back_text: 'Отдать на аутсорс', example: 'We outsource IT support.' },
    { front_text: 'Quarter', back_text: 'Квартал', example: 'Q3 results are strong.' },
    { front_text: 'Launch', back_text: 'Запуск', example: 'Product launch is next week.' },
    { front_text: 'Target', back_text: 'Цель / Мишень', example: 'We hit our sales target.' },
  ],

  // ── 3: Английский для путешествий ────────────────────────────────────────────
  3: [
    { front_text: 'Passport', back_text: 'Паспорт', example: 'May I see your passport?' },
    { front_text: 'Ticket', back_text: 'Билет', example: 'I booked two tickets.' },
    { front_text: 'Flight', back_text: 'Рейс / Полёт', example: 'My flight is at 6 AM.' },
    { front_text: 'Hotel', back_text: 'Отель', example: 'I reserved a hotel room.' },
    { front_text: 'Check in', back_text: 'Заселиться / Регистрация', example: 'Check-in is at 2 PM.' },
    { front_text: 'Check out', back_text: 'Выселиться', example: 'Check-out is at 11 AM.' },
    { front_text: 'Reservation', back_text: 'Бронирование', example: 'I have a reservation.' },
    { front_text: 'Luggage', back_text: 'Багаж', example: 'My luggage is lost.' },
    { front_text: 'Exchange rate', back_text: 'Обменный курс', example: 'What is the exchange rate?' },
    { front_text: 'Map', back_text: 'Карта', example: 'Do you have a map?' },
    { front_text: 'Where is...?', back_text: 'Где находится...?', example: 'Where is the station?' },
    { front_text: 'How much?', back_text: 'Сколько стоит?', example: 'How much does it cost?' },
    { front_text: 'Restaurant', back_text: 'Ресторан', example: 'Is there a restaurant nearby?' },
    { front_text: 'Taxi', back_text: 'Такси', example: 'Can you call a taxi?' },
    { front_text: 'Museum', back_text: 'Музей', example: 'The museum opens at 9.' },
    { front_text: 'Pharmacy', back_text: 'Аптека', example: 'I need a pharmacy.' },
    { front_text: 'Emergency', back_text: 'Скорая помощь / ЧП', example: 'Call emergency services!' },
    { front_text: 'Left', back_text: 'Налево', example: 'Turn left at the corner.' },
    { front_text: 'Right', back_text: 'Направо', example: 'The hotel is on the right.' },
    { front_text: 'Straight ahead', back_text: 'Прямо', example: 'Go straight ahead.' },
    { front_text: 'I am lost', back_text: 'Я заблудился', example: 'I am lost. Can you help?' },
    { front_text: 'Do you speak Russian?', back_text: 'Вы говорите по-русски?', example: 'Do you speak Russian?' },
    { front_text: 'Vegetarian', back_text: 'Вегетарианское', example: 'Is there a vegetarian option?' },
    { front_text: 'Bill please', back_text: 'Счёт, пожалуйста', example: 'Bill please!' },
    { front_text: 'Wi-Fi', back_text: 'Вай-фай', example: 'What is the Wi-Fi password?' },
  ],

  // ── 4: Неправильные глаголы ──────────────────────────────────────────────────
  4: [
    { front_text: 'go / went / gone', back_text: 'идти / шёл / шёл', example: 'I went to school yesterday.' },
    { front_text: 'come / came / come', back_text: 'приходить / пришёл / пришёл', example: 'She came home late.' },
    { front_text: 'do / did / done', back_text: 'делать / сделал / сделан', example: 'I did my homework.' },
    { front_text: 'see / saw / seen', back_text: 'видеть / видел / увиден', example: 'I saw that film.' },
    { front_text: 'know / knew / known', back_text: 'знать / знал / известен', example: 'I knew the answer.' },
    { front_text: 'take / took / taken', back_text: 'брать / взял / взят', example: 'He took my book.' },
    { front_text: 'get / got / got', back_text: 'получать / получил / получен', example: 'I got a letter.' },
    { front_text: 'make / made / made', back_text: 'делать / сделал / сделан', example: 'She made a cake.' },
    { front_text: 'think / thought / thought', back_text: 'думать / подумал / обдуман', example: 'I thought it was easy.' },
    { front_text: 'say / said / said', back_text: 'говорить / сказал / сказан', example: 'He said goodbye.' },
    { front_text: 'give / gave / given', back_text: 'давать / дал / дан', example: 'She gave me a gift.' },
    { front_text: 'find / found / found', back_text: 'находить / нашёл / найден', example: 'I found my keys.' },
    { front_text: 'tell / told / told', back_text: 'рассказывать / рассказал / рассказан', example: 'He told me the truth.' },
    { front_text: 'write / wrote / written', back_text: 'писать / написал / написан', example: 'I wrote a letter.' },
    { front_text: 'read / read / read', back_text: 'читать / читал / прочитан', example: 'I read that book.' },
    { front_text: 'have / had / had', back_text: 'иметь / имел / имел', example: 'I had breakfast.' },
    { front_text: 'speak / spoke / spoken', back_text: 'говорить / говорил / сказан', example: 'I spoke to the manager.' },
    { front_text: 'run / ran / run', back_text: 'бежать / бежал / бежал', example: 'She ran five miles.' },
    { front_text: 'buy / bought / bought', back_text: 'покупать / купил / куплен', example: 'I bought a new car.' },
    { front_text: 'bring / brought / brought', back_text: 'приносить / принёс / принесён', example: 'She brought flowers.' },
    { front_text: 'begin / began / begun', back_text: 'начинать / начал / начат', example: 'The film began at 8.' },
    { front_text: 'leave / left / left', back_text: 'уходить / ушёл / ушёл', example: 'He left early.' },
    { front_text: 'put / put / put', back_text: 'класть / положил / положен', example: 'Put it on the table.' },
    { front_text: 'feel / felt / felt', back_text: 'чувствовать / чувствовал / почувствован', example: 'I felt tired.' },
    { front_text: 'hear / heard / heard', back_text: 'слышать / слышал / услышан', example: 'I heard a noise.' },
  ],

  // ── 5: Испанский для начинающих ──────────────────────────────────────────────
  5: [
    { front_text: 'Hola', back_text: 'Привет', example: '¡Hola! ¿Cómo estás?' },
    { front_text: 'Buenos días', back_text: 'Доброе утро', example: 'Buenos días, señora.' },
    { front_text: 'Buenas noches', back_text: 'Доброй ночи', example: 'Buenas noches a todos.' },
    { front_text: 'Por favor', back_text: 'Пожалуйста', example: '¿Me ayudas, por favor?' },
    { front_text: 'Gracias', back_text: 'Спасибо', example: 'Muchas gracias por todo.' },
    { front_text: 'De nada', back_text: 'Пожалуйста / Не за что', example: '—Gracias. —De nada.' },
    { front_text: 'Lo siento', back_text: 'Мне жаль / Извините', example: 'Lo siento mucho.' },
    { front_text: '¿Cómo te llamas?', back_text: 'Как тебя зовут?', example: '¿Cómo te llamas tú?' },
    { front_text: 'Me llamo...', back_text: 'Меня зовут...', example: 'Me llamo María.' },
    { front_text: '¿Cuánto cuesta?', back_text: 'Сколько стоит?', example: '¿Cuánto cuesta esto?' },
    { front_text: 'El agua', back_text: 'Вода', example: 'Quiero agua, por favor.' },
    { front_text: 'La comida', back_text: 'Еда', example: 'La comida está deliciosa.' },
    { front_text: 'El baño', back_text: 'Туалет', example: '¿Dónde está el baño?' },
    { front_text: 'La calle', back_text: 'Улица', example: 'Caminamos por la calle.' },
    { front_text: 'El hospital', back_text: 'Больница', example: 'Necesito ir al hospital.' },
    { front_text: 'Hablar', back_text: 'Говорить', example: 'Quiero hablar contigo.' },
    { front_text: 'Entender', back_text: 'Понимать', example: 'No entiendo nada.' },
    { front_text: 'Querer', back_text: 'Хотеть', example: 'Quiero aprender español.' },
    { front_text: 'Ir', back_text: 'Идти', example: 'Voy a la tienda.' },
    { front_text: 'Ser / Estar', back_text: 'Быть', example: 'Soy estudiante. Estoy bien.' },
    { front_text: 'Grande', back_text: 'Большой', example: 'Es una ciudad muy grande.' },
    { front_text: 'Pequeño', back_text: 'Маленький', example: 'Mi apartamento es pequeño.' },
    { front_text: 'Bueno', back_text: 'Хороший', example: 'Es un buen libro.' },
    { front_text: 'Malo', back_text: 'Плохой', example: 'Es una mala idea.' },
    { front_text: 'Bonito', back_text: 'Красивый', example: 'Qué bonito día hace hoy.' },
  ],

  // ── 6: Испанские глаголы ─────────────────────────────────────────────────────
  6: [
    { front_text: 'Hablar', back_text: 'Говорить', example: 'Yo hablo español.' },
    { front_text: 'Comer', back_text: 'Есть', example: 'Vamos a comer ahora.' },
    { front_text: 'Beber', back_text: 'Пить', example: 'Quiero beber agua.' },
    { front_text: 'Dormir', back_text: 'Спать', example: 'Necesito dormir.' },
    { front_text: 'Trabajar', back_text: 'Работать', example: 'Él trabaja en una oficina.' },
    { front_text: 'Estudiar', back_text: 'Учиться', example: 'Ella estudia medicina.' },
    { front_text: 'Leer', back_text: 'Читать', example: 'Me gusta leer libros.' },
    { front_text: 'Escribir', back_text: 'Писать', example: 'Tengo que escribir una carta.' },
    { front_text: 'Correr', back_text: 'Бегать', example: 'Corro cada mañana.' },
    { front_text: 'Escuchar', back_text: 'Слушать', example: 'Escucho música todos los días.' },
    { front_text: 'Ver', back_text: 'Видеть / Смотреть', example: 'Veo una película.' },
    { front_text: 'Comprar', back_text: 'Покупать', example: 'Quiero comprar pan.' },
    { front_text: 'Vender', back_text: 'Продавать', example: 'Él vende coches.' },
    { front_text: 'Abrir', back_text: 'Открывать', example: 'Abre la ventana.' },
    { front_text: 'Cerrar', back_text: 'Закрывать', example: 'Cierra la puerta, por favor.' },
    { front_text: 'Volver', back_text: 'Возвращаться', example: 'Vuelvo a casa tarde.' },
    { front_text: 'Esperar', back_text: 'Ждать', example: 'Te espero aquí.' },
    { front_text: 'Ayudar', back_text: 'Помогать', example: '¿Puedes ayudarme?' },
    { front_text: 'Saber', back_text: 'Знать (факт)', example: 'No sé la respuesta.' },
    { front_text: 'Poder', back_text: 'Мочь', example: '¿Puedes venir mañana?' },
  ],

  // ── 7: Немецкие существительные с артиклями ──────────────────────────────────
  7: [
    { front_text: 'der Tisch', back_text: 'стол', example: 'Der Tisch ist groß.' },
    { front_text: 'die Tür', back_text: 'дверь', example: 'Die Tür ist geschlossen.' },
    { front_text: 'das Buch', back_text: 'книга', example: 'Das Buch ist interessant.' },
    { front_text: 'der Stuhl', back_text: 'стул', example: 'Der Stuhl ist bequem.' },
    { front_text: 'das Fenster', back_text: 'окно', example: 'Das Fenster ist offen.' },
    { front_text: 'das Haus', back_text: 'дом', example: 'Das Haus ist alt.' },
    { front_text: 'die Straße', back_text: 'улица', example: 'Die Straße ist lang.' },
    { front_text: 'der Garten', back_text: 'сад', example: 'Der Garten ist schön.' },
    { front_text: 'die Küche', back_text: 'кухня', example: 'Die Küche ist modern.' },
    { front_text: 'das Zimmer', back_text: 'комната', example: 'Das Zimmer ist sauber.' },
    { front_text: 'der Mann', back_text: 'мужчина', example: 'Der Mann arbeitet viel.' },
    { front_text: 'die Frau', back_text: 'женщина / жена', example: 'Die Frau ist nett.' },
    { front_text: 'das Kind', back_text: 'ребёнок', example: 'Das Kind spielt draußen.' },
    { front_text: 'der Hund', back_text: 'собака', example: 'Der Hund ist freundlich.' },
    { front_text: 'die Katze', back_text: 'кошка', example: 'Die Katze schläft.' },
    { front_text: 'das Auto', back_text: 'автомобиль', example: 'Das Auto ist neu.' },
    { front_text: 'der Zug', back_text: 'поезд', example: 'Der Zug kommt um 9 Uhr.' },
    { front_text: 'die Stadt', back_text: 'город', example: 'Die Stadt ist groß.' },
    { front_text: 'das Geld', back_text: 'деньги', example: 'Das Geld liegt auf dem Tisch.' },
    { front_text: 'die Arbeit', back_text: 'работа', example: 'Die Arbeit macht Spaß.' },
    { front_text: 'der Bahnhof', back_text: 'вокзал', example: 'Der Bahnhof ist in der Mitte.' },
    { front_text: 'die Schule', back_text: 'школа', example: 'Die Schule beginnt um 8 Uhr.' },
    { front_text: 'das Wasser', back_text: 'вода', example: 'Das Wasser ist kalt.' },
    { front_text: 'die Musik', back_text: 'музыка', example: 'Die Musik ist schön.' },
    { front_text: 'der Freund', back_text: 'друг', example: 'Der Freund hilft mir.' },
  ],

  // ── 8: Немецкий для начинающих ───────────────────────────────────────────────
  8: [
    { front_text: 'Hallo', back_text: 'Привет', example: 'Hallo, wie geht es dir?' },
    { front_text: 'Guten Morgen', back_text: 'Доброе утро', example: 'Guten Morgen, Herr Schmidt!' },
    { front_text: 'Guten Abend', back_text: 'Добрый вечер', example: 'Guten Abend, alle zusammen.' },
    { front_text: 'Auf Wiedersehen', back_text: 'До свидания', example: 'Auf Wiedersehen und tschüss!' },
    { front_text: 'Bitte', back_text: 'Пожалуйста', example: 'Kannst du mir helfen, bitte?' },
    { front_text: 'Danke', back_text: 'Спасибо', example: 'Danke schön für alles.' },
    { front_text: 'Entschuldigung', back_text: 'Извините', example: 'Entschuldigung, wo ist der Bahnhof?' },
    { front_text: 'Ja', back_text: 'Да', example: 'Ja, natürlich!' },
    { front_text: 'Nein', back_text: 'Нет', example: 'Nein, das stimmt nicht.' },
    { front_text: 'Wie viel kostet das?', back_text: 'Сколько это стоит?', example: 'Wie viel kostet das Brot?' },
    { front_text: 'Ich verstehe nicht', back_text: 'Я не понимаю', example: 'Ich verstehe nicht, bitte langsamer.' },
    { front_text: 'Sprechen Sie Russisch?', back_text: 'Вы говорите по-русски?', example: 'Sprechen Sie Russisch?' },
    { front_text: 'Wo ist...?', back_text: 'Где находится...?', example: 'Wo ist das Hotel?' },
    { front_text: 'Ich heiße...', back_text: 'Меня зовут...', example: 'Ich heiße Anna.' },
    { front_text: 'Wie geht es Ihnen?', back_text: 'Как вы поживаете?', example: 'Wie geht es Ihnen heute?' },
    { front_text: 'Mir geht es gut', back_text: 'Я чувствую себя хорошо', example: 'Danke, mir geht es gut.' },
    { front_text: 'Ich brauche Hilfe', back_text: 'Мне нужна помощь', example: 'Ich brauche Hilfe, bitte.' },
    { front_text: 'Links', back_text: 'Налево', example: 'Biegen Sie links ab.' },
    { front_text: 'Rechts', back_text: 'Направо', example: 'Das Büro ist rechts.' },
    { front_text: 'Geradeaus', back_text: 'Прямо', example: 'Gehen Sie geradeaus.' },
  ],

  // ── 9: Французские фразы для ресторана ───────────────────────────────────────
  9: [
    { front_text: 'Une table pour deux', back_text: 'Стол на двоих', example: 'Une table pour deux, s\'il vous plaît.' },
    { front_text: 'La carte, s\'il vous plaît', back_text: 'Меню, пожалуйста', example: 'La carte, s\'il vous plaît!' },
    { front_text: 'Je voudrais...', back_text: 'Я бы хотел...', example: 'Je voudrais un café, s\'il vous plaît.' },
    { front_text: 'L\'addition, s\'il vous plaît', back_text: 'Счёт, пожалуйста', example: 'L\'addition, s\'il vous plaît!' },
    { front_text: 'C\'est délicieux', back_text: 'Это восхитительно', example: 'C\'est délicieux! Merci.' },
    { front_text: 'Je suis allergique à...', back_text: 'У меня аллергия на...', example: 'Je suis allergique aux noix.' },
    { front_text: 'Sans gluten', back_text: 'Без глютена', example: 'Avez-vous des plats sans gluten?' },
    { front_text: 'Le plat du jour', back_text: 'Блюдо дня', example: 'Quel est le plat du jour?' },
    { front_text: 'Bien cuit', back_text: 'Хорошо прожаренный', example: 'Je voudrais mon steak bien cuit.' },
    { front_text: 'À point', back_text: 'Средней прожарки', example: 'Le steak à point, s\'il vous plaît.' },
    { front_text: 'L\'entrée', back_text: 'Закуска / Первое', example: 'Comme entrée, je prends la soupe.' },
    { front_text: 'Le dessert', back_text: 'Десерт', example: 'Pour le dessert, une crème brûlée.' },
    { front_text: 'Garçon!', back_text: 'Официант!', example: 'Garçon, s\'il vous plaît!' },
    { front_text: 'Encore un peu', back_text: 'Ещё немного', example: 'Encore un peu de vin, merci.' },
    { front_text: 'C\'est trop salé', back_text: 'Это слишком солёное', example: 'C\'est un peu trop salé pour moi.' },
    { front_text: 'À emporter', back_text: 'С собой', example: 'Je voudrais ça à emporter.' },
    { front_text: 'La terrasse', back_text: 'Терраса', example: 'Peut-on s\'asseoir en terrasse?' },
    { front_text: 'Réservation', back_text: 'Бронирование', example: 'J\'ai une réservation au nom de Dupont.' },
    { front_text: 'Végétarien', back_text: 'Вегетарианский', example: 'Avez-vous des plats végétariens?' },
    { front_text: 'Eau minérale', back_text: 'Минеральная вода', example: 'Une eau minérale, s\'il vous plaît.' },
  ],

  // ── 10: Французский для начинающих ───────────────────────────────────────────
  10: [
    { front_text: 'Bonjour', back_text: 'Добрый день / Привет', example: 'Bonjour, comment allez-vous?' },
    { front_text: 'Bonsoir', back_text: 'Добрый вечер', example: 'Bonsoir, madame.' },
    { front_text: 'Au revoir', back_text: 'До свидания', example: 'Au revoir et bonne journée!' },
    { front_text: 'Merci', back_text: 'Спасибо', example: 'Merci beaucoup!' },
    { front_text: 'S\'il vous plaît', back_text: 'Пожалуйста (просьба)', example: 'Aidez-moi, s\'il vous plaît.' },
    { front_text: 'Excusez-moi', back_text: 'Извините', example: 'Excusez-moi, où est la gare?' },
    { front_text: 'Oui', back_text: 'Да', example: 'Oui, je comprends.' },
    { front_text: 'Non', back_text: 'Нет', example: 'Non, merci.' },
    { front_text: 'Je m\'appelle...', back_text: 'Меня зовут...', example: 'Je m\'appelle Pierre.' },
    { front_text: 'Comment vous appelez-vous?', back_text: 'Как вас зовут?', example: 'Comment vous appelez-vous?' },
    { front_text: 'Je ne comprends pas', back_text: 'Я не понимаю', example: 'Désolé, je ne comprends pas.' },
    { front_text: 'Parlez-vous russe?', back_text: 'Вы говорите по-русски?', example: 'Parlez-vous russe?' },
    { front_text: 'Où est...?', back_text: 'Где находится...?', example: 'Où est le métro?' },
    { front_text: 'Combien ça coûte?', back_text: 'Сколько это стоит?', example: 'Combien ça coûte?' },
    { front_text: 'J\'ai besoin d\'aide', back_text: 'Мне нужна помощь', example: 'J\'ai besoin d\'aide, s\'il vous plaît.' },
    { front_text: 'Bien', back_text: 'Хорошо', example: 'Très bien, merci.' },
    { front_text: 'Mal', back_text: 'Плохо', example: 'Je me sens mal.' },
    { front_text: 'Grand', back_text: 'Большой', example: 'C\'est un grand appartement.' },
    { front_text: 'Petit', back_text: 'Маленький', example: 'J\'ai un petit chien.' },
    { front_text: 'Beau / Belle', back_text: 'Красивый / Красивая', example: 'Quelle belle ville!' },
  ],

  // ── 11: Итальянский для туристов ─────────────────────────────────────────────
  11: [
    { front_text: 'Ciao', back_text: 'Привет / Пока', example: 'Ciao! Come stai?' },
    { front_text: 'Buongiorno', back_text: 'Доброе утро / Добрый день', example: 'Buongiorno a tutti!' },
    { front_text: 'Grazie', back_text: 'Спасибо', example: 'Grazie mille!' },
    { front_text: 'Prego', back_text: 'Пожалуйста / Не за что', example: '—Grazie. —Prego!' },
    { front_text: 'Scusi', back_text: 'Извините', example: 'Scusi, dov\'è il bagno?' },
    { front_text: 'Quanto costa?', back_text: 'Сколько стоит?', example: 'Quanto costa questo?' },
    { front_text: 'Dov\'è...?', back_text: 'Где находится...?', example: 'Dov\'è la stazione?' },
    { front_text: 'Il conto, per favore', back_text: 'Счёт, пожалуйста', example: 'Il conto, per favore!' },
    { front_text: 'Non capisco', back_text: 'Я не понимаю', example: 'Scusi, non capisco.' },
    { front_text: 'Parla russo?', back_text: 'Вы говорите по-русски?', example: 'Parla russo o inglese?' },
    { front_text: 'Aiuto!', back_text: 'Помогите!', example: 'Aiuto! Ho perso il portafoglio.' },
    { front_text: 'Vorrei...', back_text: 'Я бы хотел...', example: 'Vorrei un caffè, per favore.' },
    { front_text: 'Un biglietto per...', back_text: 'Один билет до...', example: 'Un biglietto per Roma, per favore.' },
    { front_text: 'A sinistra', back_text: 'Налево', example: 'Giri a sinistra.' },
    { front_text: 'A destra', back_text: 'Направо', example: 'Il museo è a destra.' },
    { front_text: 'Dritto', back_text: 'Прямо', example: 'Vada sempre dritto.' },
    { front_text: 'L\'albergo', back_text: 'Отель', example: 'Dove si trova l\'albergo?' },
    { front_text: 'Il ristorante', back_text: 'Ресторан', example: 'C\'è un buon ristorante qui?' },
    { front_text: 'La farmacia', back_text: 'Аптека', example: 'Ho bisogno di una farmacia.' },
    { front_text: 'Mi chiamo...', back_text: 'Меня зовут...', example: 'Mi chiamo Marco.' },
  ],

  // ── 12: Итальянские прилагательные ───────────────────────────────────────────
  12: [
    { front_text: 'Bello / Bella', back_text: 'Красивый / Красивая', example: 'Che bello panorama!' },
    { front_text: 'Buono / Buona', back_text: 'Хороший / Хорошая', example: 'È un buon libro.' },
    { front_text: 'Grande', back_text: 'Большой', example: 'È una grande città.' },
    { front_text: 'Piccolo / Piccola', back_text: 'Маленький / Маленькая', example: 'Ho un piccolo appartamento.' },
    { front_text: 'Nuovo / Nuova', back_text: 'Новый / Новая', example: 'Ho una nuova macchina.' },
    { front_text: 'Vecchio / Vecchia', back_text: 'Старый / Старая', example: 'È un vecchio amico.' },
    { front_text: 'Alto / Alta', back_text: 'Высокий / Высокая', example: 'È un edificio molto alto.' },
    { front_text: 'Basso / Bassa', back_text: 'Низкий / Низкая', example: 'Il prezzo è basso.' },
    { front_text: 'Lungo / Lunga', back_text: 'Длинный / Длинная', example: 'È una lunga strada.' },
    { front_text: 'Corto / Corta', back_text: 'Короткий / Короткая', example: 'Ho i capelli corti.' },
    { front_text: 'Caldo / Calda', back_text: 'Тёплый / Жаркий', example: 'Oggi fa molto caldo.' },
    { front_text: 'Freddo / Fredda', back_text: 'Холодный / Холодная', example: 'L\'acqua è fredda.' },
    { front_text: 'Facile', back_text: 'Лёгкий / Простой', example: 'Questo esercizio è facile.' },
    { front_text: 'Difficile', back_text: 'Трудный / Сложный', example: 'L\'italiano è difficile.' },
    { front_text: 'Simpatico / Simpatica', back_text: 'Симпатичный / Приятный', example: 'È una persona simpatica.' },
    { front_text: 'Stanco / Stanca', back_text: 'Усталый / Усталая', example: 'Sono molto stanco oggi.' },
    { front_text: 'Felice', back_text: 'Счастливый / Радостный', example: 'Sono molto felice.' },
    { front_text: 'Triste', back_text: 'Грустный / Печальный', example: 'È una storia triste.' },
    { front_text: 'Interessante', back_text: 'Интересный', example: 'È un film molto interessante.' },
    { front_text: 'Noioso / Noiosa', back_text: 'Скучный / Скучная', example: 'La lezione è noiosa.' },
  ],

  // ── 13: Японский: хирагана ───────────────────────────────────────────────────
  13: [
    { front_text: 'あ', back_text: 'а', example: 'あおい (aoi) — синий' },
    { front_text: 'い', back_text: 'и', example: 'いぬ (inu) — собака' },
    { front_text: 'う', back_text: 'у', example: 'うみ (umi) — море' },
    { front_text: 'え', back_text: 'э', example: 'えき (eki) — станция' },
    { front_text: 'お', back_text: 'о', example: 'おかね (okane) — деньги' },
    { front_text: 'か', back_text: 'ка', example: 'かお (kao) — лицо' },
    { front_text: 'き', back_text: 'ки', example: 'きく (kiku) — слушать' },
    { front_text: 'く', back_text: 'ку', example: 'くつ (kutsu) — обувь' },
    { front_text: 'け', back_text: 'кэ', example: 'けん (ken) — меч' },
    { front_text: 'こ', back_text: 'ко', example: 'こえ (koe) — голос' },
    { front_text: 'さ', back_text: 'са', example: 'さかな (sakana) — рыба' },
    { front_text: 'し', back_text: 'си/ши', example: 'しろ (shiro) — белый' },
    { front_text: 'す', back_text: 'су', example: 'すき (suki) — любить' },
    { front_text: 'せ', back_text: 'сэ', example: 'せんせい (sensei) — учитель' },
    { front_text: 'そ', back_text: 'со', example: 'そら (sora) — небо' },
    { front_text: 'た', back_text: 'та', example: 'たべる (taberu) — есть' },
    { front_text: 'な', back_text: 'на', example: 'なまえ (namae) — имя' },
    { front_text: 'は', back_text: 'ха', example: 'はな (hana) — цветок' },
    { front_text: 'ま', back_text: 'ма', example: 'まち (machi) — город' },
    { front_text: 'や', back_text: 'я', example: 'やま (yama) — гора' },
  ],

  // ── 14: Японский для путешествий ─────────────────────────────────────────────
  14: [
    { front_text: 'こんにちは (Konnichiwa)', back_text: 'Добрый день / Привет', example: 'こんにちは！' },
    { front_text: 'ありがとう (Arigatou)', back_text: 'Спасибо', example: 'ありがとうございます。' },
    { front_text: 'すみません (Sumimasen)', back_text: 'Извините', example: 'すみません、どこですか？' },
    { front_text: 'いくらですか？ (Ikura desu ka?)', back_text: 'Сколько стоит?', example: 'これはいくらですか？' },
    { front_text: 'どこですか？ (Doko desu ka?)', back_text: 'Где находится?', example: 'トイレはどこですか？' },
    { front_text: 'わかりません (Wakarimasen)', back_text: 'Я не понимаю', example: 'すみません、わかりません。' },
    { front_text: 'えき (Eki)', back_text: 'Станция', example: 'えきはどこですか？' },
    { front_text: 'ホテル (Hoteru)', back_text: 'Отель', example: 'ホテルをよやくしました。' },
    { front_text: 'たすけて！(Tasukete!)', back_text: 'Помогите!', example: 'たすけて！' },
    { front_text: 'おいしい (Oishii)', back_text: 'Вкусно!', example: 'これはおいしい！' },
    { front_text: 'みぎ (Migi)', back_text: 'Направо', example: 'みぎにまがってください。' },
    { front_text: 'ひだり (Hidari)', back_text: 'Налево', example: 'ひだりにまがってください。' },
    { front_text: 'でんしゃ (Densha)', back_text: 'Поезд', example: 'でんしゃはなんじですか？' },
    { front_text: 'くうこう (Kuukou)', back_text: 'Аэропорт', example: 'くうこうはどこですか？' },
    { front_text: 'おみやげ (Omiyage)', back_text: 'Сувенир', example: 'おみやげをかいました。' },
    { front_text: 'しゃしん (Shashin)', back_text: 'Фотография', example: 'しゃしんをとってもいいですか？' },
    { front_text: 'でんわ (Denwa)', back_text: 'Телефон', example: 'でんわばんごうはなんですか？' },
    { front_text: 'やすい (Yasui)', back_text: 'Дешёвый', example: 'これはやすいです。' },
    { front_text: 'たかい (Takai)', back_text: 'Дорогой / Высокий', example: 'これはたかいです。' },
    { front_text: 'みず (Mizu)', back_text: 'Вода', example: 'みずをください。' },
  ],

  // ── 15: Китайский: базовые иероглифы ─────────────────────────────────────────
  15: [
    { front_text: '你好 (Nǐ hǎo)', back_text: 'Привет', example: '你好！你好吗？' },
    { front_text: '谢谢 (Xièxiè)', back_text: 'Спасибо', example: '非常谢谢你！' },
    { front_text: '对不起 (Duìbuqǐ)', back_text: 'Извините / Прости', example: '对不起，我迟到了。' },
    { front_text: '请 (Qǐng)', back_text: 'Пожалуйста', example: '请进！' },
    { front_text: '是 (Shì)', back_text: 'Да / Является', example: '是的，我是学生。' },
    { front_text: '不 (Bù)', back_text: 'Нет / Не', example: '不，谢谢。' },
    { front_text: '我 (Wǒ)', back_text: 'Я', example: '我是俄罗斯人。' },
    { front_text: '你 (Nǐ)', back_text: 'Ты', example: '你叫什么名字？' },
    { front_text: '他/她 (Tā)', back_text: 'Он / Она', example: '他是我的朋友。' },
    { front_text: '好 (Hǎo)', back_text: 'Хорошо / Хороший', example: '很好，谢谢！' },
    { front_text: '大 (Dà)', back_text: 'Большой', example: '这是一个大城市。' },
    { front_text: '小 (Xiǎo)', back_text: 'Маленький', example: '这是一只小猫。' },
    { front_text: '水 (Shuǐ)', back_text: 'Вода', example: '请给我一杯水。' },
    { front_text: '饭 (Fàn)', back_text: 'Еда / Рис', example: '我要吃饭。' },
    { front_text: '人 (Rén)', back_text: 'Человек / Люди', example: '他是一个好人。' },
    { front_text: '朋友 (Péngyǒu)', back_text: 'Друг', example: '他是我最好的朋友。' },
    { front_text: '家 (Jiā)', back_text: 'Дом / Семья', example: '我回家了。' },
    { front_text: '钱 (Qián)', back_text: 'Деньги', example: '多少钱？' },
    { front_text: '多少钱？(Duōshǎo qián?)', back_text: 'Сколько стоит?', example: '这个多少钱？' },
    { front_text: '在哪里？(Zài nǎlǐ?)', back_text: 'Где находится?', example: '厕所在哪里？' },
  ],

  // ── 16: Китайский: числа и время ─────────────────────────────────────────────
  16: [
    { front_text: '一 (Yī)', back_text: '1 — один', example: '我有一个苹果。' },
    { front_text: '二 (Èr)', back_text: '2 — два', example: '请给我两杯茶。' },
    { front_text: '三 (Sān)', back_text: '3 — три', example: '我们有三只猫。' },
    { front_text: '四 (Sì)', back_text: '4 — четыре', example: '四个人在家。' },
    { front_text: '五 (Wǔ)', back_text: '5 — пять', example: '五月是我的生日。' },
    { front_text: '六 (Liù)', back_text: '6 — шесть', example: '六点见！' },
    { front_text: '七 (Qī)', back_text: '7 — семь', example: '一周有七天。' },
    { front_text: '八 (Bā)', back_text: '8 — восемь', example: '八月很热。' },
    { front_text: '九 (Jiǔ)', back_text: '9 — девять', example: '九月开学。' },
    { front_text: '十 (Shí)', back_text: '10 — десять', example: '十点见面。' },
    { front_text: '今天 (Jīntiān)', back_text: 'Сегодня', example: '今天天气很好。' },
    { front_text: '明天 (Míngtiān)', back_text: 'Завтра', example: '明天见！' },
    { front_text: '昨天 (Zuótiān)', back_text: 'Вчера', example: '昨天我很累。' },
    { front_text: '现在 (Xiànzài)', back_text: 'Сейчас', example: '现在几点？' },
    { front_text: '星期一 (Xīngqīyī)', back_text: 'Понедельник', example: '星期一上班。' },
    { front_text: '星期三 (Xīngqīsān)', back_text: 'Среда', example: '星期三见面。' },
    { front_text: '星期五 (Xīngqīwǔ)', back_text: 'Пятница', example: '星期五是最好的一天！' },
    { front_text: '早上 (Zǎoshang)', back_text: 'Утро', example: '早上好！' },
    { front_text: '晚上 (Wǎnshang)', back_text: 'Вечер', example: '晚上好！' },
    { front_text: '年 (Nián)', back_text: 'Год', example: '今年是哪年？' },
  ],
};

module.exports = { PREBUILT_DECKS, PREBUILT_CARDS };